on:
  push:
    branches: ["master"]

name: Build and Test

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Install external test dependencies
        run: |
          sudo apt update
          sudo apt install btrfs-progs

      - name: Run tests
        run: ./test.sh
